# Creating Arrays in NumPy

NumPy provides several ways to create arrays, from Python lists, built-in functions, and special array generators. This notebook covers the most common methods.

## Import NumPy

First, import the NumPy library.

In [16]:
import numpy as np

## Creating Arrays from Python Lists

You can create a NumPy array from a Python list using `np.array()`.

In [17]:
# 1D array from list
arr1 = np.array([1, 2, 3, 4])
print(' 1D array:\n', arr1)


print()

# 2D array from nested list
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(' 2D array:\n', arr2)

print()

# 3D array from nested list
arr3= np.array([[1,2],[2,3],[3,4]])
print( ' 3D array\n',arr3)

 1D array:
 [1 2 3 4]

 2D array:
 [[1 2 3]
 [4 5 6]]

 3D array
 [[1 2]
 [2 3]
 [3 4]]


## Creating Arrays with Zeros, Ones, and Full

NumPy provides functions to create arrays filled with zeros, ones, or any constant value.

In [18]:
# Array of zeros
zeros = np.zeros((2, 3))
print('Zeros:\n', zeros)

# Array of ones
ones = np.ones((2, 3))
print('Ones:\n', ones)

# Array filled with a constant value
full = np.full((2, 3), 7)
print('Full (7s):\n', full)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Full (7s):
 [[7 7 7]
 [7 7 7]]


## Creating Arrays with arange and linspace

- `np.arange(start, stop, step)` creates arrays with regularly incrementing values.
- `np.linspace(start, stop, num)` creates arrays with a specified number of evenly spaced values between start and stop (inclusive).

In [28]:
# Using arange
arange_arr = np.arange(0, 21, 2)
print('arange:', arange_arr)

# Using linspace
linspace_arr = np.linspace(0,1, 5)
print('linspace:', linspace_arr)

arange: [ 0  2  4  6  8 10 12 14 16 18 20]
linspace: [0.   0.25 0.5  0.75 1.  ]


## Special Arrays: Identity and Eye

NumPy can create identity matrices and diagonal matrices using `np.eye()` and `np.identity()`.

In [48]:
# Identity matrix
identity = np.identity(3)
print('Identity matrix:\n', identity)

# Eye matrix (diagonal)
eye = np.eye(3, 4)
print('Eye matrix:\n', eye)

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Eye matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
