# Indexing and Slicing in NumPy

NumPy provides powerful ways to access and modify array elements through indexing and slicing. This notebook covers basic indexing, advanced indexing, boolean indexing, and fancy indexing.

## Import NumPy

In [1]:
import numpy as np

## Basic Indexing

NumPy arrays can be indexed just like Python lists, but with additional capabilities for multi-dimensional arrays.

In [8]:
# Create a 1D array
arr1d = np.array([10, 20, 30, 40, 50])
print('1D array:', arr1d)
print('First element:', arr1d[0])
print('Last element:', arr1d[-1])

# Create a 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('\n2D array:\n', arr2d)
print('Element at [0,0]:', arr2d[0, 0])
print('Element at [1,1]:', arr2d[1, 1])
print('Element at [2,2]:', arr2d[2, 2])

1D array: [10 20 30 40 50]
First element: 10
Last element: 50

2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at [0,0]: 1
Element at [1,1]: 5
Element at [2,2]: 9


## Slicing Arrays

Slicing allows you to extract portions of arrays. The syntax is `array[start:stop:step]`.

In [3]:
# Slicing 1D array
print('Original array:', arr1d)
print('First three elements:', arr1d[:3])
print('Every other element:', arr1d[::2])
print('Reverse array:', arr1d[::-1])

# Slicing 2D array
print('\nOriginal 2D array:\n', arr2d)
print('First row:', arr2d[0, :])
print('First column:', arr2d[:, 0])
print('Subarray (rows 0-1, columns 1-2):\n', arr2d[0:2, 1:3])

Original array: [10 20 30 40 50]
First three elements: [10 20 30]
Every other element: [10 30 50]
Reverse array: [50 40 30 20 10]

Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
First row: [1 2 3]
First column: [1 4 7]
Subarray (rows 0-1, columns 1-2):
 [[2 3]
 [5 6]]


## Boolean Indexing

Boolean indexing allows you to select elements based on conditions.

In [ ]:
# Boolean indexing
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print('Original array:', arr)

# Create boolean mask, masking means to filter data based on conditions.

mask = arr > 5
print('Boolean mask (arr > 5):', mask)

# Use mask to select elements
print('Elements > 5:', arr[mask])

# Direct boolean indexing
print('Even numbers:', arr[arr % 2 == 0])

# Multiple conditions
print('Elements between 3 and 8:', arr[(arr >= 3) & (arr <= 8)])

Original array: [ 1  2  3  4  5  6  7  8  9 10]
Boolean mask (arr > 5): [False False False False False  True  True  True  True  True]
Elements > 5: [ 6  7  8  9 10]
Even numbers: [ 2  4  6  8 10]
Elements between 3 and 8: [3 4 5 6 7 8]


## Fancy Indexing

Fancy indexing allows you to select elements using arrays of indices.

In [5]:
# Fancy indexing with 1D array
arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]
print('Original array:', arr)
print('Indices:', indices)
print('Fancy indexed elements:', arr[indices])

# Fancy indexing with 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('\n2D array:\n', arr2d)
row_indices = [0, 1, 2]
col_indices = [0, 2, 1]
print('Row indices:', row_indices)
print('Col indices:', col_indices)
print('Fancy indexed elements:', arr2d[row_indices, col_indices])

# Using fancy indexing to modify elements
arr[indices] = [100, 200, 300]
print('\nModified array:', arr)

Original array: [10 20 30 40 50]
Indices: [0, 2, 4]
Fancy indexed elements: [10 30 50]

2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Row indices: [0, 1, 2]
Col indices: [0, 2, 1]
Fancy indexed elements: [1 6 8]

Modified array: [100  20 200  40 300]


## Summary

You have learned the different ways to index and slice NumPy arrays:
- Basic indexing for accessing individual elements
- Slicing for extracting subarrays
- Boolean indexing for conditional selection
- Fancy indexing for selecting with arrays of indices

These techniques are essential for efficient data manipulation in NumPy.