# Array Operations in NumPy

NumPy provides efficient operations on arrays, including arithmetic operations, broadcasting, reshaping, and concatenation. This notebook covers the most common array operations.

## Import NumPy

In [1]:
import numpy as np

## Multiplication Operations

NumPy arrays support multiplication of rows and columns.

In [ ]:
#create 1D array
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
product = arr1 * arr2
print('Element-wise multiplication of arr1 and arr2:\n', product, "\n")

# Create 2D arrays and perform element-wise multiplication
arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[5, 6], [7, 8]])
product = arr3 * arr4
print('Element-wise multiplication of arr3 and arr4:\n', product, "\n")

# Identity matrix
identity_matrix = np.eye(3)
print('Identity matrix of size 3x3:\n', identity_matrix,  "\n")

# Matrix multiplication
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
matrix_product = np.dot(matrix1, matrix2)
print('Matrix multiplication of matrix1 and matrix2:\n',matrix_product,"\n")

# Element-wise multiplication of 2D arrays
elementwise_product = matrix1 * matrix2
print('Element-wise multiplication of matrix1 and matrix2:\n', elementwise_product, "\n")


Element-wise multiplication of arr1 and arr2:
 [ 4 10 18] 

Element-wise multiplication of arr3 and arr4:
 [[ 5 12]
 [21 32]] 

Identity matrix of size 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

Matrix multiplication of matrix1 and matrix2:
 [[19 22]
 [43 50]] 

Element-wise multiplication of matrix1 and matrix2:
 [[ 5 12]
 [21 32]] 



: 

## Arithmetic Operations

NumPy arrays support element-wise arithmetic operations.

In [2]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print('a:', a)
print('b:', b)
print('a + b:', a + b)
print('a - b:', a - b)
print('a * b:', a * b)
print('a / b:', a / b)
print('a ** 2:', a ** 2)
print('a % b:', a % b)

a: [1 2 3]
b: [4 5 6]
a + b: [5 7 9]
a - b: [-3 -3 -3]
a * b: [ 4 10 18]
a / b: [0.25 0.4  0.5 ]
a ** 2: [1 4 9]
a % b: [1 2 3]


## Broadcasting

Broadcasting allows operations between arrays of different shapes by automatically expanding the smaller array.

In [ ]:
# Broadcasting examples
arr = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 10

print('Array:\n', arr)
print('Scalar:', scalar)
print('Array + scalar:\n', arr + scalar)

# Broadcasting with different shapes
arr1 = np.array([[1], [2], [3]])  # Shape (3, 1)
arr2 = np.array([10, 20, 30])     # Shape (3,)

print('\narr1 shape:', arr1.shape)
print('arr2 shape:', arr2.shape) 
print('arr1 + arr2:\n', arr1 + arr2)

Array:
 [[1 2 3]
 [4 5 6]]
Scalar: 10
Array + scalar:
 [[11 12 13]
 [14 15 16]]

arr1 shape: (3, 1)
arr2 shape: (3,)
arr1 + arr2:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


## Reshaping Arrays

You can change the shape of arrays using `reshape()` or `resize()`.

In [4]:
arr = np.arange(12)
print('Original array:', arr)
print('Shape:', arr.shape)

# Reshape to 2D
reshaped = arr.reshape(3, 4)
print('\nReshaped to (3, 4):\n', reshaped)

# Reshape to 3D
reshaped_3d = arr.reshape(2, 2, 3)
print('\nReshaped to (2, 2, 3):\n', reshaped_3d)

# Flatten array
flattened = reshaped_3d.flatten()
print('\nFlattened:', flattened)

# Transpose
transposed = reshaped.T
print('\nTransposed:\n', transposed)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,)

Reshaped to (3, 4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped to (2, 2, 3):
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]

Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transposed:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## Concatenation and Splitting

NumPy provides functions to concatenate and split arrays.

In [5]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print('Array a:\n', a)
print('Array b:\n', b)

# Concatenate along axis 0 (rows)
concat_axis0 = np.concatenate((a, b), axis=0)
print('\nConcatenated along axis 0:\n', concat_axis0)

# Concatenate along axis 1 (columns)
concat_axis1 = np.concatenate((a, b), axis=1)
print('\nConcatenated along axis 1:\n', concat_axis1)

# Stack arrays
stacked = np.stack((a, b))
print('\nStacked arrays shape:', stacked.shape)
print('Stacked arrays:\n', stacked)

# Split array
arr = np.arange(10)
print('\nOriginal array:', arr)
split_arr = np.split(arr, 5)
print('Split into 5 parts:', split_arr)

Array a:
 [[1 2]
 [3 4]]
Array b:
 [[5 6]
 [7 8]]

Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]

Stacked arrays shape: (2, 2, 2)
Stacked arrays:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Original array: [0 1 2 3 4 5 6 7 8 9]
Split into 5 parts: [array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


## Summary

You have learned key array operations in NumPy:
- Arithmetic operations (element-wise)
- Broadcasting for operations on different shapes
- Reshaping arrays with `reshape()` and `flatten()`
- Concatenation and splitting arrays

These operations form the core of data manipulation in NumPy.